name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  testing:
    name: Lint Check, Unit tests and build debug
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'    
      # Step 2: Get base endpoint url
      - name: Access BASE_URL
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: echo BASE_URL=\"$BASE_URL\" > ./local.properties

      # Step 3: Check the code with ktlint, you can remove this job if you don't use ktlint
      - name: Run Kotlin Linter
        run: ./gradlew ktlintCheck

      # Step 3: Check the code with Android linter
      - name: Run Android Linter
        run: ./gradlew lintDebug

      # Step 4: Yun your unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Step 4: Assemble debug apk to send to firebase test lab
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

      # Upload apk to download  
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
            name: App
            path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk

# jobs:
#   unit_tests:
#     runs-on: [ubuntu-latest]
#     steps:
#       - uses: actions/checkout@v2
#       - name: set up JDK 11
#         uses: actions/setup-java@v2
#         with:
#           java-version: '11'
#           distribution: 'adopt'    
#       - name: Access BASE_URL
#         env:
#           BASE_URL: ${{ secrets.BASE_URL }}
#         run: echo BASE_URL=\"$BASE_URL\" > ./local.properties
#       - name: Grant execute permission for gradlew
#         run: chmod +x gradlew
#       - name: Unit tests
#         run: ./gradlew testDebugUnitTest

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: set up JDK 11
#       uses: actions/setup-java@v2
#       with:
#         java-version: '11'
#         distribution: 'adopt'    
#     - name: Access BASE_URL
#       env:
#         BASE_URL: ${{ secrets.BASE_URL }}
#       run: echo BASE_URL=\"$BASE_URL\" > ./local.properties
#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
#     - name: Build Debug APK
#       run: ./gradlew :app:assembleDebug
#     - name: Upload APK
#       uses: actions/upload-artifact@v2
#       with:
#         name: App
#         path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
